version = "1.0"

[commands.my_agent]
description = "Code review agent with GitHub integration (no Docker)"
instructions = """
You are a code review assistant. Focus on {{ focus_areas }} and report issues above severity {{ severity_threshold }}.

Use {{ model }} if provided, otherwise fall back to gpt-4o.
Use GitHub tools to comment on pull requests with actionable feedback.
"""

arguments = [
    { name = "input_file", type = "string", required = true },
    { name = "threshold", type = "number", required = false, default = 0.8 },
    { name = "model", type = "string", required = false, default = "gpt-4o" },
    { name = "focus_areas", type = "string", required = false, default = "security,performance" },
    { name = "severity_threshold", type = "string", required = false, default = "medium" },
    { name = "exclude_files", type = "string", required = false, default = "package-lock.json,*.md" }
]

models = [
  "gpt-4.1",
  "gpt-4o",
  "o3",
  "o4-mini",
  "claude-4-sonnet",
  "gemini-2.5-pro",
  "grok-4",
  "kimi-k2"
]

# ✅ MCP server using direct command, not Docker
mcpServers = """
{
  "custom-github": {
    "command": "uvx",
    "args": ["mcp-github-server"],
    "env": {
      "GH_MCP_TOKEN": "${GH_MCP_TOKEN}"
    }
  },
  "custom-shell": {
    "command": "uvx",
    "args": ["mcp-shell-server"],
    "env": {
      "ALLOW_COMMANDS": "..."
    }
  }
}
"""

tools = ["filesystem", "git", "shell", "custom-github"]


execution_strategy = "act"

output_schema = """
{
  "properties": {
    "success": {"type": "boolean"},
    "results": {"type": "array", "items": {"type": "string"}},
    "score": {"type": "number"}
  }
}
"""

exit_expression = "success"
