version = "1.0"

[commands.review_pr]
description = "Code review agent for GitHub PRs, focused on security and performance."
instructions = """
You are a senior code reviewer. Review code diffs in PRs for security and performance concerns.
Return only suggestions above the severity threshold, and skip docs or config-only changes.
"""

arguments = [
  { name = "target_branch", type = "string", required = true },
  { name = "severity_threshold", type = "string", required = false, default = "medium" },
  { name = "focus_areas", type = "string", required = false, default = "security,performance" },
  { name = "exclude_files", type = "string", required = false, default = "package-lock.json,*.md" },
  { name = "include_suggestions", type = "boolean", required = false, default = true },
  { name = "models", type = "string", required = false, default = "gpt-4o,o4-mini" }
]

# Custom MCP servers required when using --no-builtin
mcpServers = """
{
  "custom_shell": {
    "command": "uvx",
    "args": ["mcp-shell-server"],
    "env": { "ALLOW_COMMANDS": "*" }
  },
  "github": {
    "command": "gh",
    "args": ["api", "--method=POST"],
    "env": { "GITHUB_TOKEN": "${GH_TOKEN}" }
  },
  "git": {
    "command": "uvx",
    "args": ["mcp-git-server"]
  },
  "filesystem": {
    "command": "uvx",
    "args": ["mcp-fs-server"]
  },
  "ripgrep": {
    "command": "uvx",
    "args": ["mcp-ripgrep-server"]
  }
}
"""

tools = ["git", "filesystem", "ripgrep", "github", "custom_shell"]

execution_strategy = "act"

output_schema = """
{
  "properties": {
    "success": { "type": "boolean" },
    "results": { "type": "array", "items": { "type": "string" } },
    "score": { "type": "number" }
  }
}
"""

exit_expression = "success"
