- name: Run code review agent
  uses: qodo-ai/command@v1
  env:
    QODO_API_KEY: ${{ secrets.QODO_API_KEY }}
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
    GH_MCP_TOKEN: ${{ secrets.GH_MCP_TOKEN }}

  with:
    prompt: code-review
    no-builtin: true  # ✅ Properly disables built-in servers to avoid conflict
    agent-file: agent.toml
    key-value-pairs: |
      target_branch=${{ github.base_ref }}
      severity_threshold=medium
      focus_areas=security,performance
      exclude_files=package-lock.json,*.md
      include_suggestions=true
      models=gpt-4.1,gpt-4o,o3,o4-mini,claude-4-sonnet,gemini-2.5-pro,grok-4,kimi-k2
